version: "3.5"
services:

  #Le Service de Registre Docker
  registry:
    image: registry:2.7
    container_name: registry
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
#      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#      REGISTRY_AUTH: htpasswd
#      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
#      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
#      REGISTRY_LOG_LEVEL: debug
#      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
#      REGISTRY_AUTH_TOKEN_REALM: https://gitlab.example.com/jwt/auth    # Change url here
#      REGISTRY_AUTH_TOKEN_SERVICE: container_registry
#      REGISTRY_AUTH_TOKEN_ISSUER: gitlab-issuer
#      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/gitlab-registry.crt
#      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - /registry_data/data:/var/lib/registry
      #- ./registry_data/certs:/certs
      #- ./registry_data/auth:/auth
#    labels:
#      - "traefik.enable=true"
#      - "traefik.frontend.rule=Host:registry.gitlab.example.com"      # Change registry host here
#      - "traefik.port=5000"
#      - "traefik.backend=gitlab-registry"
#      - "traefik.frontend.entryPoints=http,https"
    networks:
      net_backend:
        ipv4_address: 172.21.1.19
        aliases:
          - registry
#networks:
#  net_backend:
#    external:
#      name: lugar_net_backend


networks:
  net_backend:
    driver: bridge
    #internal: true
    ipam:
      config:
        - subnet: 172.21.1.0/24
