version: '3'

services:
  postgres-keycloak:
      image: postgres
      container_name: postgres-keycloak
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: Lugar2020
  keycloak:
      image: quay.io/keycloak/keycloak:11.0.2
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres-keycloak
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: Lugar2020
        KEYCLOAK_USER: Lugar
        KEYCLOAK_PASSWORD: Lugar2020
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 9200:8080
      depends_on:
        - postgres-keycloak
network:
  driver: bridge
  ipam:
    