{
 "title": "Zabbix - VM Monitoring",
 "description": "Monitor your VMware Virtual Machines using Zabbix and Grafana",
 "tags": [
  "zabbix",
  "vcenter",
  "host",
  "vm",
  "vsphere"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "GuestVMs", "label": "Virtual Machine", "query": "{Virtual machines}{*}" },
   {
    "name": "TotalDisk",
    "label": "Total Disk",
    "query": "{Virtual machines}{*}{Filesystems}{*}"
   },
   { "name": "ESXHost", "query": "{Hypervisors}{*}" }
  ]
 },
 "panels": [
  { "title": "$GuestVMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "GuestVMs" },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Power state" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "# CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Number of virtual CPUs" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Committed storage space" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interfaces Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*Number of bytes received on interface (.*)/",
        "$1:Rx"
       ],
       "text": "replaceAlias(/.*Number of bytes received on interface (.*)/, $1:Rx)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*Number of bytes transmitted on interface (.*)/",
        "$1:Tx"
       ],
       "text": "replaceAlias(/.*Number of bytes transmitted on interface (.*)/, $1:Tx)"
      }
     ],
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "/.*Number of bytes*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ESX Host",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Hypervisor name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Memory size" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Ballooned memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Compressed memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Guest memory usage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Host memory usage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Private memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Shared memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "Swapped memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "CPU usage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*Free disk space on (.*).*\\(percentage\\)/",
        "$1"
       ],
       "text": "replaceAlias(/.*Free disk space on (.*).*\\(percentage\\)/, $1)"
      }
     ],
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$GuestVMs" },
     "item": { "filter": "/.*Free.*percen/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}