version: "3.5"

#Liste des servies
services:

  #Le service Jenkins
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    env_file:
      - .env_jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
    ports: 
      - "2000:8080"
      - "50000:50000"
    networks:
     net_backend:
      ipv4_address: 172.21.0.6
      aliases:
       - jenkins
    restart: unless-stopped
    tty: true

networks:
  net_backend:
    external:
      name: lugar_net_backend