version: '3.7'

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    image: minio/minio:RELEASE.2020-09-17T04-49-20Z
    container_name: minio1
    volumes:
      - /home/bzile/cloub-minio/data1-1:/data1
      - /home/bzile/cloub-minio/data1-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: Lugar
      MINIO_SECRET_KEY: Lugar2020
    command: server http://minio{1...4}/data{1...2}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9500/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      net_backend:
        ipv4_address: 172.21.0.29
        aliases:
          - minio1

  minio2:
    image: minio/minio:RELEASE.2020-09-17T04-49-20Z
    container_name: minio2
    volumes:
      - /home/bzile/cloub-minio/data2-1:/data1
      - /home/bzile/cloub-minio/data2-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: Lugar
      MINIO_SECRET_KEY: Lugar2020
    command: server http://minio{1...4}/data{1...2}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9500/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      net_backend:
        ipv4_address: 172.21.0.28
        aliases:
          - minio2

  minio3:
    image: minio/minio:RELEASE.2020-09-17T04-49-20Z
    container_name: minio3
    volumes:
      - /home/bzile/cloub-minio/data3-1:/data1
      - /home/bzile/cloub-minio/data3-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: Lugar
      MINIO_SECRET_KEY: Lugar2020
    command: server http://minio{1...4}/data{1...2}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9500/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      net_backend:
        ipv4_address: 172.21.0.27
        aliases:
          - minio3
  minio4:
    image: minio/minio:RELEASE.2020-09-17T04-49-20Z
    container_name: minio4
    volumes:
      - /home/bzile/cloub-minio/data4-1:/data1
      - /home/bzile/cloub-minio/data4-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: Lugar
      MINIO_SECRET_KEY: Lugar2020
    networks:
      net_backend:
        ipv4_address: 172.21.0.26
        aliases:
          - minio4
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9500/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9500:9500"
    networks:
      net_backend:
        ipv4_address: 172.21.0.25
        aliases:
          - nginx
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
#volumes:
#  data1-1:/home/bzile/cloub-minio/
#  data1-2:/home/bzile/cloub-minio/
#  data2-1:/home/bzile/cloub-minio/
#  data2-2:/home/bzile/cloub-minio/
#  data3-1:/home/bzile/cloub-minio/
#  data3-2:/home/bzile/cloub-minio/
#  data4-1:/home/bzile/cloub-minio/
#  data4-2:/home/bzile/cloub-minio/

networks:
  net_backend:
    external:
      name: lugar_net_backend